### ISSUE TITLE
 Android M (SDK 23)

### ISSUE THREAD

**Issue by Artestico** [Estimote/Android-SDK#138]
The project work perfectly with (SDK 22) but when i upgrade my gradle to (SDK 23) i have this error : 

com.estimote.sdk.SystemRequirementsHelper.checkAllPermissions:167 Your app is targeting Android M (SDK 23). You need to acquire one the location permissions: ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION.

My main project have this two permission of ACCESS_COARSE_LOCATION & ACCESS_FINE_LOCATION  because i use it in the geolocation .

**Comment by heypiotr** [comment]
Android M requires your app to request extra permissions in order to be able to scan for beacons. See the following section in our README:

https://github.com/Estimote/Android-SDK#android-m-and-runtime-permissions

Note that it's not enough to just have them in your manifest file, you also need to request them at runtime. You can use the `SystemRequirementsChecker` to do that. If you need any help with that, feel free to post on our forums: https://forums.estimote.com
