### ISSUE TITLE
`checkWithDefaultDialogs` doesn't try to turn bluetooth on for the second time

### ISSUE THREAD

**Issue by lwasylkowski** [Estimote/Android-SDK#155]
Because `DefaultRequirementsCheckerCallback` is a singleton, when user chooses not to enable bluetooth once, all subsequent calls to `checkWithDefaultDialogs` will not ask to enable bluetooth again. 

Solution to this would probably be not to keep callback as a singleton, or modify

```
public DefaultRequirementsCheckerCallback setActivity(android.app.Activity activity) {
        if(this.activity != activity) {
            this.alreadyStarted = false;
        }

        this.activity = activity;
        return this;
    }
```

method to properly clean up callback's state, including `bluetoothDenied` field

**Comment by pawelDylag** [comment]
Hello @lwasylkowski !

Thanks for reporting that! I will definitely check that out and fix it soon :)

Have a nice day!

**Comment by pawelDylag** [comment]
Hello once again @lwasylkowski,

I decided not to incorporate this change into our SDK. The fact is, that we don't want to spam our users with constantly popping alerts with bluetooth requests. If user denies turning Bluetooth on, it will stop asking again, until application is restarted - and this behaviour is intentional.  If you are not happy with that - you can simply create your own implementation with custom modifications :)

Have a nice day!

**Comment by lwasylkowski** [comment]
Although I disagree, I understand the reasoning (and I ended up building own requirements checker). But then at the very least I think current behaviour should be better documented. Thanks!
