### ISSUE TITLE
Android 4.4.2, Could not find class 'android.bluetooth.le.ScanFilter$Builder'

### ISSUE THREAD

**Issue by mwarnaar** [Estimote/Android-SDK#159]
Good day,

running the Estimote SDK v.0.10.8 on a Huawei Y360-U61 running android 4.4.2 (API 19), an error pops up in logcat with the following message:

> E/dalvikvm: Could not find class 'android.bluetooth.le.ScanFilter$Builder', referenced from method com.estimote.sdk.eddystone.internal.EddystoneUtils.createEddystoneScanFilter
> E/dalvikvm: Could not find class 'android.bluetooth.le.ScanFilter$Builder', referenced from method com.estimote.sdk.service.internal.NearableUtils.createNearableScanFilter

It does not terminate/crash the application, but I don't get this error running on a OnePlus 3 (Android 6.)

The real problem is that after a while, no Estimote beacons (I'm doing a test with 16 beacons spread accross a floor of about 50m in length) are returned in the `onBeaconsDiscovered` callback. However, using an additional 2 BeaconInside beacons operating on a stronger signal level (-3dBm compared to -16 on the Estimotes), keep working correctly while ranging. The SDK seems to have no problem with them. Turning bluetooth off and on causes it to work for a while, then the same thing happens again. I'm not sure if the missing class error relates to this phenomenon, but it might.

**Comment by pawelDylag** [comment]
Hello @mwarnaar!

I'm sorry for duch delay - if you haven't figured something out, let me explain. 
ScanFilters were introduced in [Android API level 21](https://developer.android.com/reference/android/bluetooth/le/BluetoothLeScanner.html).
Because of that, there is a problem with uploading filters for older android versions.
For testing purposes, there is a flag in our SDK to manually turn off hardware filtering - but I strongly recommend you, not to use this flag on your production code. You need to add into your Android Manifest:
` <meta-data android:name="disable_hardware_filtering" android:value="true" /> `
It may help with such problems. Anyway, you should update your Android system, because this error was fixed some time ago in Android, as far as I know :)

Have a nice day!

**Comment by francisco-rg** [comment]
try what you said @pawelDylag , in Android 4.4.4 on a Galaxy A5 (SM-A500M), i'm having the same issues, never get's any beacon, using Estimote android sdk 1.4.0 

compileSdkVersion 27
buildToolsVersion "27.0.1"
minSdkVersion 18
targetSdkVersion 27

everything works on 5.0 >

this other messages might be unrelated but just in case:

11-23 17:36:49.641 32063-32063/com.xxxx D/Deals: [onCreate] Estimote Start SDK / Manager / Regions
11-23 17:36:49.661 32063-32063/com.xxxx I/dalvikvm: Could not find method android.app.Activity.shouldShowRequestPermissionRationale, referenced from method com.estimote.coresdk.common.requirements.SystemRequirementsHelper.shouldShowCoarseLocationRequestPermissionRationale
11-23 17:36:49.661 32063-32063/com.xxxx W/dalvikvm: VFY: unable to resolve virtual method 128: Landroid/app/Activity;.shouldShowRequestPermissionRationale (Ljava/lang/String;)Z

thanks for your help
