### ISSUE TITLE
EstimoteCloud.fetchBeaconDetails(deviceId, ...)

### ISSUE THREAD

**Issue by Sharprender** [Estimote/Android-SDK#167]
If I use the function EstimoteCloud.fetchBeaconDetails(deviceId, ...),
I get "onSuccess" the BeaconInfo object.
But the problem is, that the beaconInfo.macAddress has more than 6 octets and is equal to deviceId.

for example:

```
deviceId=a67452f482c6743389d6f791bc88dd02

beaconInfo.macAddress=[A6:74:52:F4:82:C6:74:33:89:D6:F7:91:BC:88:DD:02]
```

I have this issue on Android 6.01 Samsung Galaxy S6 edge.
Estimote SDK version 0.11.1

**Comment by pawelDylag** [comment]
Hello @Sharprender 

`EstimoteCloud.fetchBeaconDetails(...)` is our old endpoint for proximity beacons. 
I assume that you are using Location Beacon or newer Proximity beacon - for such, we have prepared different cloud structure. I encourage you to use method `EstimoteCloud.fetchDeviceDetails(...)` for getting device details. 
Please bear in mind, that our old beacon's have their deviceId equal to their mac address. Since firmware 4.0.0 we are using deviceId DIFFERENT than mac address. 
I hope that it helps you somehow :)

Have a nice day!
