### ISSUE TITLE
Android 6.0 beacon search problem

### ISSUE THREAD

**Issue by t7ank** [Estimote/Android-SDK#174]
Hey!

We have found bug on Android 6.0 (not 6.0.1) devices. We have tried devices OUKITEL K6000 and UMi Super, where update of Android software is not possible to 6.0.1. On all other 15+ phones (A4.4, A5.1.1, A6.0.1,..)  that we tested on, it works perfect.
Ranging returns empty array of beacon MAC addresses on those 2 models, on other phones work fine. We have received a mac address twice on OUKITEL, when we left it running for a long time, but they disapeared after just few more loops.

Is this known bug for OS A6.0, is problem in "cheap" smartphone manufacturers or is it SDK bug?

EDIT: We are using Estimote SDK 0.11.0. and only one region search for ranging and one for monitoring. Just saw that you have released 0.12.0... We will test it.

**Comment by pawelDylag** [comment]
Hello @t7ank !

The problem is that "cheap" phones have sometimes really crappy BLE stack, which results in many bugs on a scanner level. The only idea that comes to my mind is that maybe those phones use batch scanning, which is a mechanism for better battery performance - but at the cost of responsiveness. Some devices have huge problems with delivering proper results in batch scan mode. I would kindly suggest you to update SDK to 0.12.0 at first - we disabled batch scanning by default in this version. Let me know if this problem still occurs :)

**Comment by t7ank** [comment]
We have tested new SDK. Warnings are gone on "cheap" phones.
New SDK did find beacons faster with monitoring sometimes, but not always (we did wait 45s for beacons to disapear). Ranging still does not work. 
We had also tried CUBOT S600 with A5.1.1 and it worked fine. It is big possibility that it is a smartphone manufacturers fault.
Thanks for reply.

**Comment by pawelDylag** [comment]
@t7ank - t7anks for info :)
You might want also to try flag `DISABLE_HARDWARE_FILTERING` - cheap phones have sometimes problems with hardware filters, which results in empty scan reports. But be careful - this also will increase battery drain on other phones, and cause a lot of scan reports being received by our sdk. 
I hope you will come to a good solution
