### ISSUE TITLE
Unable to build the project with latest Android Studio version

### ISSUE THREAD

**Issue by Kameswari** [Estimote/Android-SDK#177]
Hi,

Recently I have upgraded my Android Studio with 2.2.2 and I am unable to build Notification project under Examples folder. While doing gradle sync, I am getting the below error.

Information:Gradle tasks [clean, :app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies]
Error:com.android.builder.internal.aapt.AaptException: Failed to crunch file D:\Android_Studio_Projects\Samples\Estimote-Android-SDK\Android-SDK-master\Examples\Notification\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.1.0\res\drawable-xxhdpi\abc_textfield_search_activated_mtrl_alpha.9.png into D:\Android_Studio_Projects\Samples\Estimote-Android-SDK\Android-SDK-master\Examples\Notification\app\build\intermediates\res\merged\debug\drawable-xxhdpi\abc_textfield_search_activated_mtrl_alpha.9.png
Error:Execution failed for task ':app:mergeDebugResources'.
> Error: com.android.builder.internal.aapt.AaptException: Failed to crunch file D:\Android_Studio_Projects\Samples\Estimote-Android-SDK\Android-SDK-master\Examples\Notification\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.1.0\res\drawable-xxhdpi\abc_textfield_search_activated_mtrl_alpha.9.png into D:\Android_Studio_Projects\Samples\Estimote-Android-SDK\Android-SDK-master\Examples\Notification\app\build\intermediates\res\merged\debug\drawable-xxhdpi\abc_textfield_search_activated_mtrl_alpha.9.png
Information:BUILD FAILED
Information:Total time: 8.021 secs
Information:2 errors
Information:0 warnings
Information:See complete output in console

Please resolve this asap as I have some tight deadlines. Thanks in advance.

Regards,
Kam

**Comment by pawelDylag** [comment]
Hello @Kameswari 

From your log I can deduce that ':app:mergeDebugResources' gradle task is trying to prepare your resources, and `com.android.support\appcompat-v7\23.1.0\res\drawable-xxhdpi\abc_textfield_search_activated_mtrl_alpha.9.png ` is going in the way. This is nothing to do with our SDK as far as I suspect. 
If you are using WIndows, this might help: https://stackoverflow.com/questions/18556280/android-studio-unable-to-open-png-file
Otherwise, I would try the solutions from stackoverflow issues - It seems to be a lot of them. 

Have a nice day!
