### ISSUE TITLE
When monitoring secure beacons, SDK repeatedly sends onEnteredRegion / onExitRegion 

### ISSUE THREAD

**Issue by ehssanh** [Estimote/Android-SDK#179]
When monitoring 2 or more beacons, Estimote SDK repeatedly sends onEneteredRegion() / onExitRegion() callbacks with only milliseconds of difference in time. 
The issue occurs at least on the following phones / Android OS versions:
Samsung S4 / Android 5.0.1
Asus Zenfone 2E / Android 5.0.1
Nexus 6p / Android 7. 

Some filtered Logs:
[short_logs.txt](https://github.com/Estimote/Android-SDK/files/595605/short_logs.txt)

Here are Detailed Logs: 
[detail_logs.txt](https://github.com/Estimote/Android-SDK/files/595604/detail_logs.txt)

**Comment by julestburt** [comment]
Can you tell us if there's been any movement with this issue we reported - thx.

**Comment by pawelDylag** [comment]
Hello @julestburt , @ehssanh 

Could you confirm if this is still happening in version `1.0.3` ?

Cheers!

**Comment by francisco-rg** [comment]
Also Galaxy Note 3 (SM-N900) and Note 5 (SM-N920G)
On android 5.0 and 7.0 respectively
from the version 1.0.3 to current 1.4.0

 compileSdkVersion 27
buildToolsVersion "27.0.1"
minSdkVersion 18
targetSdkVersion 27

but trying since version 23

**Comment by pawelDylag** [comment]
I encourage you to try our new **ProximitySDK** 🚀 - it is dedicated for creating proximity interactions with our beacons - its main focus is to deliver the reliable enter/exit experience according to a different zones of beacons, based on our own data-science, and Estimote Monitoring packet. 
**It works extremely well with Android 5.0-8.0 devices** (full support for Nougat, and Oreo included), and also allows you to configure it to keep scanning in the background.

As it comes for security, there is no support for it in ProximitySDK, **yet** ;) 

Here is the official repository page ->  https://github.com/Estimote/Android-Proximity-SDK

Also, we keep posting updates about the progress of our development [**on this thread at our forums**](https://forums.estimote.com/t/estimote-android-sdk-official-progress-reports/7450). 
**I encourage you to track it in order to be super up-to-date** :)

Please, check the mentioned [new SDK](https://github.com/Estimote/Android-Proximity-SDK) - the current SDK will soon be deprecated, and we will support only critical issues for some time.
