### ISSUE TITLE
No beacon ranged when used on IntentService

### ISSUE THREAD

**Issue by loc02998375** [Estimote/Android-SDK#188]
Hi. On Android 7.1, I'm able to start scanning and ranging beacon using the latest SDK in an Activity. However, when the same monitor and range codes are moved to an IntentService, the scan seems to be started but no beacon is ranged. 

Here is the device I tested this on: Nexus 6p, Android 7.1.1. 

The setup is very basic:
`EstimoteSDK.initialize(this, appId, appToken);
        EstimoteSDK.enableDebugLogging(true);

        final BeaconManager beaconManager = new BeaconManager(this);

        final Region region = new Region(appId, UUID.fromString(uuid), null, null);

        beaconManager.setMonitoringListener(new MonitoringListener() {
            @Override
            public void onEnteredRegion(Region region, List<Beacon> list) {
                Log.e("TEST", "Region entered: " + region.getProximityUUID());
                beaconManager.startRanging(region);
            }

            @Override
            public void onExitedRegion(Region region) {
                Log.e("TEST", "Region exited: " + region.getProximityUUID());
            }
        });

        beaconManager.setRangingListener(new RangingListener() {
            @Override
            public void onBeaconsDiscovered(Region region, List<Beacon> list) {
                Log.e("TEST", "Beacons discovered: " + list.toString());
            }
        });

        beaconManager.connect(new ServiceReadyCallback() {
            @Override
            public void onServiceReady() {
                Log.e("TEST", "Service is ready");

                beaconManager.startMonitoring(region);
            }
        });`

Here are the logs when using on IntentService:
`02-16 10:54:40.305 18165-18197/com.example.locnguyen.myapplication D/EstimoteSDK: com.estimote.sdk.service.internal.bluetooth.LollipopBluetoothAdapter.start:248 STARTED SCAN
02-16 10:54:50.325 18165-18165/com.example.locnguyen.myapplication D/EstimoteSDK: com.estimote.sdk.service.internal.bluetooth.NougatScanScheduler.onAlarmTick:166 Scheduler received alarm tick. Type = SYSTEM_ALARM
02-16 10:54:50.327 18165-18197/com.example.locnguyen.myapplication W/EstimoteSDK: com.estimote.sdk.service.internal.bluetooth.NougatScanScheduler$1.run:190 Scheduler stopping scan
02-16 10:54:50.339 18165-18197/com.example.locnguyen.myapplication D/BluetoothAdapter: STATE_ON
02-16 10:54:50.347 18165-18197/com.example.locnguyen.myapplication D/EstimoteSDK: com.estimote.sdk.service.internal.bluetooth.LollipopBluetoothAdapter.stop:278 STOPPED SCAN`

**Update:** I tried the same code on a Google Pixel XL running Android 7.1 and neither Activity nor IntentService are able to range any beacon.

**Comment by dhavalshahmi** [comment]
Same issue facing. Ranging list size comes  0, though there are 3 beacons present around device.

**Comment by pawelDylag** [comment]
Hello guys, 

Sorry for the delay - we are working hard to improve our scanning stack. Soon there will be a new release with many updates, stay tuned :)

**Comment by loc02998375** [comment]
Hi, the 1.0.0 update solves the issue but not completely. I have tried it on a number of Android 7.0+ devices and some seem to work fine, the Google Pixel, however, still will not range.

**Comment by pawelDylag** [comment]
Hey @loc02998375 

We are investigating the problem on Pixel phones, will post any info soon :)

Stay tuned!

**Comment by pawelDylag** [comment]
I encourage you to try our new **ProximitySDK** 🚀 - it is dedicated for creating proximity interactions with our beacons - its main focus is to deliver the reliable enter/exit experience according to a different zones of beacons, based on our own data-science, and Estimote Monitoring packet. 
**It works extremely well with Android 5.0-8.0 devices** (full support for Nougat, and Oreo included), and also allows you to configure it to keep scanning in the background.

Here is the official repository page ->  https://github.com/Estimote/Android-Proximity-SDK

Also, we keep posting updates about the progress of our development [**on this thread at our forums**](https://forums.estimote.com/t/estimote-android-sdk-official-progress-reports/7450). 
**I encourage you to track it in order to be super up-to-date** :)

Please, check the mentioned [new SDK](https://github.com/Estimote/Android-Proximity-SDK) - the current SDK will soon be deprecated, and we will support only critical issues for some time.
