### ISSUE TITLE
Your Android SDK documentation has to be fixed

### ISSUE THREAD

**Issue by spapas** [Estimote/Android-SDK#190]
Please improve your Android SDK documentation. See also issue #189. 

Please understand that offering an example is not as helpful as offering good java docs.

The docs don't explain almost nothing and I have to resort to checking the decompiled source code (since the code is nowhere to be found) to resolve some of my questions.  

Thank you

**Comment by pawelDylag** [comment]
Hello once again @spapas, 

I'd love to hear your feedback about our API!
If you have some more questions, feel free to PM me on my company mail pawel.dylag@estimote.com so maybe we can find a way to improve our docs quality :)

**Comment by spapas** [comment]
Here are some things I had problems with and there was no documentation:

* Vector (https://estimote.github.io/Android-SDK/JavaDocs/com/estimote/sdk/telemetry/Vector.html): How can I access the individual x/y/z values from a Vector? 
* Telemetry (https://estimote.github.io/Android-SDK/JavaDocs/com/estimote/sdk/cloud/model/Telemetry.html): You should explain a little about each attribute (for example what does it do, what's the measurement unit etc). Also, Telemetry contains a GPIO array (with four boolean values) that is not documented at all. You should add it there and explain what's each one of the four elements of that array.
* In ConfigurableDevicesScanner (https://estimote.github.io/Android-SDK/JavaDocs/com/estimote/sdk/connection/scanner/ConfigurableDevicesScanner.html) you write: "Note: This scanner should not be used for long term scanning (in background)". What should be used instead if somebody wants to continusly scan for devices to connect to?
* In ConfigurableDevicesScanner.ScannerCallback (https://estimote.github.io/Android-SDK/JavaDocs/com/estimote/sdk/connection/scanner/ConfigurableDevicesScanner.ScannerCallback.html) there's nothing to explain it. My question though is when will the `onDevicesFound` callback be called? When a device is found or once per period?
* In BulkUpdater (https://estimote.github.io/Android-SDK/JavaDocs/com/estimote/sdk/connection/scanner/BulkUpdater.html): What's this about? There's no text in the docs.
* In Gpio (https://estimote.github.io/Android-SDK/JavaDocs/com/estimote/sdk/connection/settings/Gpio.html): It is not clear how the GPIO values can be read and written. Please provide a full example about the data and config methods (for read and werite). How should the callback be used? Also, I can't understand how dataNotify() works
* EstimoteSDK (https://estimote.github.io/Android-SDK/JavaDocs/com/estimote/sdk/EstimoteSDK.html): It is not clear to me which methods require the initialize() method (passing the appId/token) to be called before calling them. Also, what does initialize() do? What I should do if I have many (java) threads in the same Android application? Should I call initialize() once per thread or once per application?

These are only some of the problems I found in the docs. As a general comment try to add a little text/description to all classes / interfaces to explain what they do - this will be very helpful to people reading the javadocs.

Thanks and best regards,
Serafeim

**Comment by pawelDylag** [comment]
Great to read that - this is a kind of feedback I really appreciate. It's not just:  "It doesn't work, do something about this" stuff.
Ok, so let me explain briefly some things. Other fixes will be of course introduced and we will update our docs throughly.

- **Vector** - we will definitely fix this - fields were declared `private` by mistake. 
- **Telemetry** - sure, will add more explanations - probably more info about possible value ranges etc.
-  **ConfigurableDevicesScanner** - we made some improvements and scanning for configurable devices will be managed via BeaconManager since next release - one place to rule them all :) You need to be patient, because we need to fully test whole functionality, but it will allow you to do some background scanning for any packet you want (including `ConfigurableDevice`)
-  **ConfigurableDevicesScanner.Callback** - same as above. Currently it calls listener every 2s.
- **Bulk updater** - It updates settings and firmware of your devices nearby. I will add more description to the interface. 
- **GPIO** - I don't have much time now to write the whole tutorial. For now you can read our [blog post](http://blog.estimote.com/post/145508085365/extending-the-power-of-your-beacons-with-gpio) about GPIO. I will add more explanations in docs of course. 
- **EstimoteSDK** - initialize() called with app id/token allows our SDK to connect with your Cloud account. So if you want to take advantage of all beacon management possibilities, you need to call initialize(). If you want to avoid any threading issues I would suggest initializing our SDK before you use it. One idea is to extend `Application` class and init our SDK there. Object of this class lives through all the lifecycle of your application and is created at the very first step. 

As an additional comment - I am aware of package/documentary/convention issues, and I can assure you that our next release will be much more focused on making our API more transparent. It will come at the cost of some "breaking changes" but well, we need to do that anyway :) 
We are still in the middle of the iteration, so be patient - I will notify you when the next version will be available. 

Oh, and I will release some quick fixes for GPIO/Vector issues tomorrow morning, so stay tuned :)

Have a great day and thanks for the constructive feedback :)

**Comment by spapas** [comment]
Hello @pawelDylag thank you very much for the very useful info! For the Vector fields I wasn't sure if it was a bug or I had missed something so I actually retrieved the x/y/z values using reflection.

I'm looking forward for the next version of the SDK - background scanning for `ConfigurableDevice` will be very useful! 

Best regards,
Serafeim

**Comment by spapas** [comment]
Hello @pawelDylag, a couple of more questions about some internal things of Estimotes: We are using BeaconManager to listen to Estimote Telemetry readings. Although there's a working prototype app, there are some things that are not clear to me from the docs (http://estimote.github.io/Android-SDK/JavaDocs/com/estimote/sdk/BeaconManager.html):

- How exactly the BeaconManager behaves when scanning? I see there's a ```setForegroundScanPeriod``` and a ```setBackgroundScanperiod```. When each one of these two is used? Why the one is called ?foreground and the other background scan? 
- I see that setForeground is for ranging only? What exactly is "ranging". From some tests I found out that, for Telemetry I need to set the foreground scan period to have a different reading for my telemetry readings (when I change the background scan period nothing happens for telemetry) - is this the correct behavior?
- There are actually 8 listener interfaces: ```BeaconManager.EddystoneListener BeaconManager.ErrorListener BeaconManager.LocationListener BeaconManager.MonitoringListener BeaconManager.NearableListener BeaconManager.RangingListener BeaconManager.ScanStatusListener 	BeaconManager.TelemetryListener```, could you explain what each one of them does and where each one needs to be used? I am only using TelemetryListener for now. Please explain what the others do (I have an idea about some of them but it'd be great if we had them all together for reference).
- What's the delay until a change in telemetry values is seen? Actually, I see very big delays when telemetry values are changed. I have a setup my application (it's an Android service actually) to listen to the telemetry readings using BeaconManager's setTelemetryListener. The callback I use just prints the current ambient light value. Now, with the default values I see one ambient light value each second (default values of foreground scan period: http://estimote.github.io/Android-SDK/JavaDocs/com/estimote/sdk/BeaconManager.html#setForegroundScanPeriod-long-long-) however when the value is changed (I put the estimote in a drawer) I keep getting the old value for around 15 seconds and then I receive the new value (so the estimote is for 15 seconds inside the drawer and I keep getting around 20 in ambient light). This is the value that is printed from the telemetry listener which is called directly from the beaconmanager so there's not a problem of my architecture. Is this the intended behavior? I would expect the light value to change immediately (i.e when I close the drawer I'd expect to see 0 to ambient light immediately). Why I get such delays? Is there a way to improve this? 

Thanks for any help!

**Comment by pawelDylag** [comment]
Hello @spapas 
I decided to write short explanation of basic terms in our SDK. I will update our main github doc soon with these data, so maybe it would be easier for developers to understand the differences. Let me know if anything is still blurry for you. Also, as for your problem with telemetry readings - this is an known issue, will be fixed in next release :)

|    | Discovery | Ranging | Monitoring
| ------------- | ------------- | ------------- | ------------- |
| Scan type | foreground | foreground | background | 
| Scan result | single packets | region | region | 
| Available packets | ConfigurableDevice, Eddystone, EstimoteTelemetry, EstimoteLocation, Nearable | Beacon region | Beacon region | 

**Foreground** - Scan is being scheduled with use of internal Estimote scheduling mechanism. Results are delivered precisely at given periods and readings are much more responsive than in background. This does not allow for scanning when app is killed or in background - there is no possibility to invoke periodical scans outside of an app. Use monitoring instead if you need this kind of behaviour. 

**Background** - Scan is being scheduled with Android alarm mechanism which allows to scan when app is in background/killed. Potential drawback of this mechanism is that results may be delivered with delay - system alarms are inexact. Although this allows to reduce battery drain and notify your app when it is in background. 

**Single packet** - Received packet from scanned device. It is the most basic data that can be acquired via discovery. Each time the device advertises new packet (depends on device’s advertising interval and TX power) the listener should be notified about this fact. There are some cases, when data is too large to fit into one BLE packet, so it is splitted into two or more frames and advertised separately. The discovery time is longer, because we need to wait for two (or more) packets in order to merge them. Telemetry readings are a good example for this case.

**Region** - Defines zone for “geo-fencing” like behaviour. This is an abstraction level a top of single packets. You can define region using iBeacons, or any other set of rules and predicates - like a set of Configurable devices, or bunch of Mirror devices. The region is used mostly to catch enter/exit events without focusing on constantly updating distance - except Ranging. 

**Discovery** - constant scan in foreground for packets of given type. 

**Ranging** - constant scan in foreground for devices in given Region. 

**Monitoring** - background scanning for enter/exit events in given Region.

**Comment by spapas** [comment]
Hello @pawelDylag thank you for the very useful information! This makes everything more clear for our use cases. I hope the next release that improves the telemetry response time will come soon!

Best regards,
Serafeim

**Comment by pawelDylag** [comment]
Hello @spapas !

[Version 1.0.0](https://github.com/Estimote/Android-SDK) is now available! I made some fix ups to our [javadocs](http://estimote.github.io/Android-SDK/JavaDocs/) as you requested. Also there are some breaking changes - don't worry, use [this guide](https://github.com/Estimote/Android-SDK/blob/master/Docs/switching_to_1.0.0.md) to migrate your old codebase. 
Also I updated our front Github page with my explanation of monitoring/ranging. 
Let me know what you think - we are still working on improving our stack, so stay tuned for next releases :) All feedback is welcome!

**Comment by spapas** [comment]
Hello @pawelDylag great stuff! One thing I'd like to recommend is to update the changelog with the correct latest version (it's still on 0.16): https://github.com/Estimote/Android-SDK/blob/master/CHANGELOG.md

I'll try to update our application to use the latest version of the Estimote API and come back with any issues / feedback. In the meantime I think that since the docs have improved you can just close this issue. Thanks!

**Comment by pawelDylag** [comment]
Changelog is now updated :) Stay tuned for future improvements! 
Let me know about any problems you encounter!
