### ISSUE TITLE
Android Things Support

### ISSUE THREAD

**Issue by compyy** [Estimote/Android-SDK#208]
Hello,

Do you have any plan to write short tutorial to use Estimote Beacons with Android Things, is it officially tested ?

Thanks.

**Comment by pawelDylag** [comment]
Hey @compyy !

This is a really interesting case! We didn't do any tests (nor tutorials) for this platform yet, but we silently keep an eye on it's evolution :) Because it's not related to our current SDK, I would recommend you to describe your desired use case [at our forums](https://forums.estimote.com/).

Cheers!

**Comment by compyy** [comment]
We are working on a project where RPI3 is configured as Gateway, it detects beacon in range and uploads the status on the internet, we are using it with Rasbian plus node library, but if we can replace it with Android things on RPI3, then we get official sdk support from estimote.

**Comment by compyy** [comment]
I did the first test with Android things, and its working, so far no issue noticed, just performs as normal Android, you just need to add few permissions in advance in manifest, and reboot the RPI3 after installing apk (strange way to fix the permission) but it works :)

**Comment by pawelDylag** [comment]
Hey @compyy !

Great to hear that :) I was playing with Android Things in my free time, and I came to the same conclusion. Good luck with your development and let me know about any problems you encounter :)

**Comment by CrossPT** [comment]
@compyy Hi! Can you tell me what permissions you add to the manifest? I'm currently getting a  

> E/EstimoteSDK: LollipopBluetoothAdapter$1.onScanFailed:244 Unable to start BLE scanning. Error code: 4

**Comment by pawelDylag** [comment]
Hey @CrossPT! 

I stumbled across this problem not so long time ago. Here is a solution:
BLE on Android Things is disabled by default. You need to either use `bluetoothAdapter.enable()` in your code first, or enable it just as a typical user on Android phone would do ( via clicking the Bluetooth button on a screen). If you are using display in your project, then you can use `DefaultPermissionsChecker` from our SDK to display a popup to enable bluetooth and click `enable` then. Without the display, you need to enable it manually using ADB shell. Try this:
```
am start -a android.bluetooth.adapter.action.REQUEST_ENABLE
```
Let me know if it works :)

**Comment by CrossPT** [comment]
Hi @pawelDylag! Long time no see :)

I don't have a display attached to it, since I don't need to show a UI. I turn the bluetooth on via `bluetoothAdapter.enable()`, checking if blueooth is enabled via a handler, then creating the beaconManager, but it keeps giving error code 4.

Logcat below:

> D/BluetoothAdapter: enable(): BT already enabled!
I/EstimoteSDK: BeaconService.onCreate:79 Creating beacon service for android version 26
D/MainActivity: Sucessfully connected to EST Beacon Service...
D/MainActivity: Starting ranging...
I/vndksupport: sphal namespace is not configured for this process. Loading /vendor/lib/hw/gralloc.gbm.so from the current namespace instead.
V/EstimoteSDK: BeaconService.startRanging:172 Start iBeacon ranging: 
V/StudioProfiler: StudioProfilers agent attached.
V/StudioProfiler: Acquiring Application for Events
V/StudioProfiler: Transformed class: java/net/URL
W/pt.streamline.rpi_batatas: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
W/zygote: Verification of void java.net.URL.checkSpecifyHandler(java.lang.SecurityManager) took 198.865ms
V/StudioProfiler: Memory control stream started.
D/BluetoothAdapter: isLeEnabled(): ON
E/EstimoteSDK: LollipopBluetoothAdapter$1.onScanFailed:244 Unable to start BLE scanning. Error code: 4

**Comment by pawelDylag** [comment]
Ok, I know what might be wrong. Our SDK uses some fancy settings using BluetoothLeScanner, and some of them are not supported on some hardwares. Although we prepared support for Android phones, we did not do proper tests for Android Things stuff. We will check that, but it's not on our priority list right now :) 

You can try using Monitoring, or setting foreground scan period to 0 - this might help, but I'm not sure.
