### ISSUE TITLE
Can't connect to my  3 months old Stickers

### ISSUE THREAD

**Issue by zubaliy** [Estimote/Android-SDK#210]
What did you change to the Estimote App from Play Market that I'm not able to connect to my Stickers anymore. i also don't see any configuration, like: advertising intervals, Tx, etc. Also Firmware update button is not working?

**Comment by pawelDylag** [comment]
Hello @zubaliy 

Sad to hear that. Unfortunately, this repository is connected to our SDK, not the App itself. Please consider posting your problems at our forums [here](https://forums.estimote.com/c/android-sdk)

As far as I know, our current Play Store app is using older SDK, which had some problems with connecting to stickers. This should be fixed in next App release :)

If you don't want to wait, please feel free to write your own app using our SDK.
