### ISSUE TITLE
Beacon not found after updating firmware to 4.11.0

### ISSUE THREAD

**Issue by ldimitroff** [Estimote/Android-SDK#217]
I'm using the latest version of the estimote sdk: **com.estimote:sdk:1.0.3:release@aar** 

Beacons where detected propperly on beacon version **4.9.x**. After firmware update there is no recognition of the beacon sdk.
Neither the EstimoteApp can find it anymore.

Any help?

**Comment by manishpatelgt** [comment]
@ldimitroff  As I m facing the same issue. I was planning to update firmware but no more now. 
It's too risky to purchase beacons because they are not providing  proper support for Android latest version. I saw lots of issues in latest SDK 1.0.3 @pawelDylag  When will you solve all the issue so that we can easily explain situation to Client ?

**Comment by pawelDylag** [comment]
Hello @ldimitroff , @manishpatelgt 

Sorry for the delay - we've been very busy lately.
1. Check if sdk `1.0.0` detects those beacons - this will tell us if our latest changes are the problem
2. What is the latest firmware version on your beacons (is it 4.11.0?)
3. What exactely are you trying to detect - are you monitoring/ranging for iBeacon packets, or just ConfigurableDevices? I need to know which protocol packet is affected. 

Don't worry guys, we'll figure it out ;)
