### ISSUE TITLE
False onExitedRegion callbacks while Monitoring/Ranging

### ISSUE THREAD

**Issue by pujaagrawal1** [Estimote/Android-SDK#229]
Hi

We are monitoring for beacons in the background using a Service. We have often noticed that the device falsely raises a "onExitedRegion" callback, even when the device is right next to the beacon.

Same issue with Ranging - We are ranging for beacons when app is in foreground mode and we get "onBeaconsDiscovered" list size as 0, when the app is right next to the beacon.

We have tested with single/multiple beacons both. Correct beacon detection is very crucial to our app, so please guide us with this !!!

For ref : 
Device -    Samsung Galaxy A7
OS       -     Android M - 6.0
SDK Version - 1.0.1

Also, we have set --- 
```
beaconManager.setBackgroundScanPeriod(200, 0);
beaconManager.setForegroundScanPeriod(200, 0);
```

**Comment by xcastoreo** [comment]
Hi @pujaagrawal1,

the signal emission of the beacons is not a perfect **sphere** around the beacon. So it is possible that you are in a zone where the signal is **attenuated**. Have you tried moving the phone around the beacon so you get the more **powerful signal zone**?

**Comment by pujaagrawal1** [comment]
@xcastoreo 
Thank you for the pointer. But the beacons will be wall mounted in our application and therefore it will not be always possible to move the phone..to detect a signal zone.

Moreover my issue is that, the beacon is right next to the device, at a distance of 1 finger..Then how come we get false callbacks ?

**Comment by davidtaylorsomo** [comment]
Hi @xcastoreo,

I'm seeing the same problems as the OP on various devices and in an earlier SDK 0.15 and the latest (1.0.3 at the time of writing). Today, I've connected a phone to a computer and monitored ADB events with a beacon at a constant 30cm (clear line of sight), and monitored the Exit and Entered events. The phone screen is constantly on and the app is running in the background (following the Estimote tutorials).

I ended up plotting the times between events in a histogram (Entered -> Exit, labelled "Time in Range" below, and Exited -> Entered, labelled "Reconnect time" below.)

![chart_time_in_range](https://user-images.githubusercontent.com/13100168/27343035-aa53a22e-55d9-11e7-9f40-52ae57631bfb.png)

![chart_time_to_reconnect](https://user-images.githubusercontent.com/13100168/27343086-cde9df28-55d9-11e7-8397-7600af39d543.png)

The test device in question is a Samsung S7 running 6.0.1 but I've also seen it on a Nexus 6P on 7.1.2 and 8.0.0 beta.

I've been changing the background and foreground times without much luck. This data was taken with 6s for each and for both scan period and wait times.

Any pointers on how to maintain a connection will be greatly appreciated.

**Comment by pawelDylag** [comment]
Hello all!

Thanks for reporting this problem! 
We are aware of it, especially happening on 7.0 devices. More improvements are on their way, but we need some more time to fully test all the cases. I'll keep you all informed about the progress :)

**Comment by pawelDylag** [comment]
Hey! 

We have released version `1.0.9` with slightly changed scanning mechanism on Nougat devices. Please confirm this issue still occurs :)

**Comment by pujaagrawal1** [comment]
Hi @pawelDylag ,

I have upgraded to 1.3.0 but now, the onExitedRegion callback of monitoring never happens. onEnterRegion events are good, but the SDK doesn't register beacon loss on monitoring.

Please help/guide !!

**Comment by pawelDylag** [comment]
I encourage you to try our new **ProximitySDK** 🚀 - it is dedicated for creating proximity interactions with our beacons - its main focus is to deliver the reliable enter/exit experience according to a different zones of beacons, based on our own data-science, and Estimote Monitoring packet. 
**It works extremely well with Android 5.0-8.0 devices** (full support for Nougat, and Oreo included), and also allows you to configure it to keep scanning in the background.

Here is the official repository page ->  https://github.com/Estimote/Android-Proximity-SDK

Also, we keep posting updates about the progress of our development [**on this thread at our forums**](https://forums.estimote.com/t/estimote-android-sdk-official-progress-reports/7450). 
**I encourage you to track it in order to be super up-to-date** :)

Please, check the mentioned [new SDK](https://github.com/Estimote/Android-Proximity-SDK) - the current SDK will soon be deprecated, and we will support only critical issues for some time.
