### ISSUE TITLE
Unreliable nearable discovery

### ISSUE THREAD

**Issue by K1N5L4Y3R** [Estimote/Android-SDK#242]
While using `onNearablesDiscovered()`, I can see that almost half of the times this is run (~45% in a 5 mins. test run of my app) the device cannot identify a Sticker that is sitting right next to it. The longest period of inactivity is almost one minute, while the average inactivity period is about 10 seconds. After these periods, it identifies the sticker again.

I'm using a Nexus 4 and can confirm that the Estimote app is also buggy in this device (i.e. sometimes it cannot find nor connect to stickers), so do you think this is a hardware problem? Do you have any suggestions to improve this?

PS: Tried contacting support via email with the same issue, but got no response at all.

**Update**: I can confirm that this not only applies to stickers (nearables), since I made one of my other stickers send iBeacon packets and used `startMonitoring()` and `setMonitoringListener()` as if I was using a regular Beacon, and I can see that the device exits and enters the region constantly, which also appears to indicate that the device looses connection with the sticker, even when sending iBeacon packets.

**Comment by daupawar** [comment]
Same thing is happening with me, 
`onNearablesDiscovered` return me list of nearables first time, when i move or shake nearable list returns empty
e.g - 
first time list return all nearables
when i make any movement with nearable, the moved nearable does not appear in the list.

```
mBeaconManager = new BeaconManager(context);
mBeaconManager.setNearableListener(this);
mBeaconManager.connect(this);
```

```
@Override
public void onServiceReady() {
        Logg.i("onServiceReady", "onServiceReady service");
        startMonitoringRegisteredBeacon();
    }
private void startMonitoringRegisteredBeacon() {
        mBeaconManager.startTelemetryDiscovery();
        mBeaconManager.startNearableDiscovery();
}
```

```
@Override
public void onNearablesDiscovered(List<Nearable> list) {
       if (list.size() > 0) {
            for (Nearable nearable : list) {
                Log.i("onNearablesDiscovered", nearable.identifier);
            }
       }
}
```

**Comment by ahmedbey** [comment]
> first time list return all nearables
> when i make any movement with nearable, the moved nearable does not appear in the list.
Exactly the same thing happens on my android TV Box Mini M8 S+ (android 6.0). The signal strength and responsiveness are weak. The worst thing is that whenever i start moving sticker it disappears from the List<Nearable>.  The official Estimote app is able to discover stikers. But it can't fetch sticker's data from the Estimote Cloud.

I have tested the same (my) program on ZTE Blade V7 lite. In SDK version 1.0.3 stickers worked well but sometimes (i couldn't manage why). However, when my program wasn't able to find any stiker the same thing was happening with the official Estimote app. And it never was able to fetch sticker's data from the Estimote Cloud. With SDK 1.0.10-1.0.13 my app and the official app don't see any sticker on ZTE. 

I'm not sure that all these problems are related to our android devices. The bad thing is that on iPad 3 everything works great - reaction on moving stickers, signal strength and stickers discovery.

**Comment by ahmedbey** [comment]
Come on, Guys! I've tested on Nexus 5x with Android 7.1  and Samsung J5 with Android 6.0 with EstimoteSDK 1.1.0. The result is the same bad! Stickers work, but responsiveness and discovery are unreliable!

**Comment by pawelDylag** [comment]
As it comes for security, there is no support for it in ProximitySDK, **yet** ;) 


I encourage you to try our new **ProximitySDK** 🚀 - it is dedicated for creating proximity interactions with our beacons - its main focus is to deliver the reliable enter/exit experience according to a different zones of beacons, based on our own data-science, and Estimote Monitoring packet. 
**It works extremely well with Android 5.0-8.0 devices** (full support for Nougat, and Oreo included), and also allows you to configure it to keep scanning in the background.

The nearables are not supported, **yet** ;)

Here is the official repository page ->  https://github.com/Estimote/Android-Proximity-SDK

Also, we keep posting updates about the progress of our development [**on this thread at our forums**](https://forums.estimote.com/t/estimote-android-sdk-official-progress-reports/7450). 
**I encourage you to track it in order to be super up-to-date** :)

Please, check the mentioned [new SDK](https://github.com/Estimote/Android-Proximity-SDK) - the current SDK will soon be deprecated, and we will support only critical issues for some time.

**Comment by TakeTheMasksOff** [comment]
I have your stickers dev kit from July 2017. They all have Nearable OS SA 1.3.0 firmware version and SB0 hardware revision. I have tested them with different devices: iPhone 6, iPad3 on iOS and Xiaomi Mi A1 with Android 7.1, Samsung J5(2016) with Android 7 and 6, several  TV boxes running with Android 7, 6, 5.1. And it wasn't possible to discover stickers at all with CS918 TV Box (with Rockchip 3188 Android 4.4 and Rockchip 3229 CPU Android 5.1). I have found only 2 devices which work with stickers as fast and responsive as iOS devices: Samsung Galaxy Tab E and CS918S TV Box (Allwinner A31 chip and external antenna)  which both have Android 4.4. And it seems like Android 4.0-4.4 is the only version of the OS that can quickly discover stickers.
My Android application was tested with Estimote SDK starting from 1.0.8 to 1.4.0. I did not find the dependency of stickers' responsiveness on the version of SDK.
Dear @pawelDylag currently it is not possible to create any reliable app on Android with stickers using Android SDK. You are going to deprecate it. But are you going to support them in ProximitySDK? **When?** 
And when Mirrors will be available for order? Your Community Manager Alexandra Socha  said that "we're currently improving its features". Does it mean that you have issues with Mirrors?

**Comment by pawelDylag** [comment]
Hey @TakeTheMasksOff 

As for now, we are deeply focused on delivering the stuff for beacons in `ProximitySDK`. Nearable scanning is already supported in `ProximitySDK`, but since it is alpha, we are not officially announcing it yet - we need to make some decisions on where to put the whole support (as a separate lib, or as a part of an existing SDK). 
But don't worry - keep calm, and read the tutorial on how to scan your `Nearables` using our new scanning mechanism here -> 
https://github.com/Estimote/Android-SDK/issues/231#issuecomment-347882415

Regards, 
Paweł

**Comment by TakeTheMasksOff** [comment]
@pawelDylag thank you! But please do not forget about stickers users, we need full supported responsive SDK
