### ISSUE TITLE
Background monitoring eats a lot of battery

### ISSUE THREAD

**Issue by lopei** [Estimote/Android-SDK#249]
Hello guys. 
In my project we are doing 24/7 background monitoring and the GPS eats almost all the battery power. Is there a way to reduce battery usage?
Background monitoring period is currently 15 seconds and sleep period is 5 minutes

**Comment by pawelDylag** [comment]
I encourage you to try our new **ProximitySDK** 🚀 - it is dedicated for creating proximity interactions with our beacons - its main focus is to deliver the reliable enter/exit experience according to a different zones of beacons, based on our own data-science, and Estimote Monitoring packet. 
**It works extremely well with Android 5.0-8.0 devices** (full support for Nougat, and Oreo included), and also allows you to configure it to keep scanning in the background.

Here is the official repository page ->  https://github.com/Estimote/Android-Proximity-SDK

Also, we keep posting updates about the progress of our development [**on this thread at our forums**](https://forums.estimote.com/t/estimote-android-sdk-official-progress-reports/7450). 
**I encourage you to track it in order to be super up-to-date** :)

Please, check the mentioned [new SDK](https://github.com/Estimote/Android-Proximity-SDK) - the current SDK will soon be deprecated, and we will support only critical issues for some time.
