### ISSUE TITLE
Android tutorial only works when Estimote app is opened

### ISSUE THREAD

**Issue by enreas** [Estimote/Android-SDK#252]
I've been following the [Android tutorial](http://developer.estimote.com/android/tutorial/part-1-setting-up/). Surprisingly, it only works if, after launching the example app, I open the official [Estimote App](https://play.google.com/store/apps/details?id=com.estimote.apps.main&hl=en), and touch **Configuration** to show the beacons in range.

This same behaviour happens when executing the example Notifications taken from the [Estimote SDK for Android](https://github.com/Estimote/Android-SDK).

What am I missing?

**Comment by enreas** [comment]
I've been testing with and Android 5.0 (Lollipop) device the tutorial it's working. A pity it doesn't work with the Android 6.0 and 7.0 devices I've tested.

**Comment by wafel82** [comment]
Hi,
Thanks for reporting this issue.
Could you provide SDK version you are observing the issue on and the phones' models you are using?
We'll investigate this issue and let you know as soon as we discover something.

Regards
Wojtek

**Comment by enreas** [comment]
SDK version: 1.1.0.
Tutorial doesn't work in: Cubot Note S, Android 6.0.
Tutorial works in: Lenovo Tab2A7-10F, Android 5.0.

**Comment by enreas** [comment]
Just for your information, I've just tested the sample app with the new [SDK 1.2.0](https://github.com/Estimote/Android-SDK/releases/tag/1.2.0) with identical results.

**Comment by MBach** [comment]
Hello,
Same issue here with SDK 1.4.0 on Android 6.0. Is there any progress on this problem?

**Comment by wafel82** [comment]
Hey @MBach, @enreas  -  sorry for delayed response, We're currently super-focused on making our new sdk-stack to be production ready.

I've tried to reproduce this issue on Nexus 6P and Pixel devices hosting Android 7 and 8 with no luck -  tutorials app works as expected for me :/
We'll try to reproduce it on different devices/OS version and let you know about results.

Please note that our current SDK (reachable by `compile 'com.estimote:sdk:1.4.0'` and referenced in current tutorials) **will be deprecated in near future**. 

I encourage you to try our new ProximitySDK 🚀 - it is dedicated for creating proximity interactions with our beacons - its main focus is to deliver the reliable enter/exit experience according to a different zones of beacons, based on our own data-science, and Estimote Monitoring packet.
It works extremely well with Android 5.0-8.0 devices (full support for Nougat, and Oreo included), and also allows you to configure it to keep scanning in the background.

Here is the official repository page -> https://github.com/Estimote/Android-Proximity-SDK

Also, we keep posting updates about the progress of our development on this thread at our forums.
I encourage you to track it in order to be super up-to-date :)

Please, check the mentioned new SDK - the current SDK will soon be deprecated, and we will support only critical issues for some time.

**Comment by MBach** [comment]
Hello @wafel82 

Thank you for your answer. I will try your new SDK tomorrow, because on 2 devices (Galaxy S7 7.0 and low budget phone 6.0) for the same code, I don't have the same behavior when implementing my own `BeaconManager.MonitoringListener()`.

Events `onEnteredRegion` are not fired on 6.0, sometimes not on 7.0 when Estimote App isn't running! For `onExitedRegion` it's more complicated, because it's almost never fired! I have followed very carefully the tutorial, (activated flip-to-sleep for testing) and tried to tweak various parameters, like `setBackgroundScanPeriod`.

**Comment by MBach** [comment]
Indeed @wafel82, I've tried https://github.com/Estimote/Android-Proximity-SDK and it's working great, much more than this SDK. 
Good job!
