### ISSUE TITLE
Wrong RSSI on Samsung Galaxy Tab A6 SM-T280

### ISSUE THREAD

**Issue by MarcoMirisola** [Estimote/Android-SDK#267]
Hi there, 
I'm having a lot of trouble detecting beacon on SM-T280 (Android 5.1.1), the device recognize the beacons correctly but the RSSI value of beacons is pretty the same (-45 , -47) even if I'm using beacons meters away (One beacon close to the device and the other ~5mt, tried with different distance), so I cant estimate the nearest beacon.
I've tried with different beacons and different devices (same model).
All works well on other devices model.
Could you please help me to understand why this happen?

**Comment by Poberro** [comment]
How this problem is related to our SDK? Which version of SDK are you using? Does other apps (BLE scanners) return different results? 
You can generate HCI snoop log as described here: 
[https://blog.bluetooth.com/debugging-bluetooth-with-an-android-app](https://blog.bluetooth.com/debugging-bluetooth-with-an-android-app)
Then we can analyse logs (in Wireshark) and determine if problem lies in low level BT controller, Android BT Stack or our SDK. RSSI value is passed pretty much untouched across BT stack. 
Also knowing  your beacon settings would help (like transmit power). RSSI is logarithmic, if your beacon advertises with maximal power, 2dBm difference might be quite a distance.
