### ISSUE TITLE
moto E4 plus scanning stop

### ISSUE THREAD

**Issue by rajeshkanna777** [Estimote/Android-SDK#268]
Am using moto e4 plus today only i bought this few minutes scannin after that tollay scannig stoped

**Comment by Poberro** [comment]
What SDK your are using? What version exactly? What Android do you have there? Have you tried using Proximity SDK?
Have you checked if you can scan using different SDKs/apps?
Have you checked logcat for any BLE related errors/warnings?
Some Androids prevented starting/stopping scans frequently.

**Comment by rajeshkanna777** [comment]
version :7.1.1 moto e4 plus
estimote sdk version:'com.estimote:sdk:1.4.0'
am doing startRanging 
i tried estimote app from play store some time scan happen some time stop so that time i turned OFF and ON bluetooth the scan happen some time and stop scanning

**Comment by Poberro** [comment]
Can you provide some logs from logcat (not filtered by application, so you can see system logs)? It looks like old SDK might be turning on and off scanning and after few times Android blocks it. I would suggest using [Proximity SDK](https://github.com/Estimote/Android-Proximity-SDK) that should have that fixed. 
Have you managed to test it on different phone?

**Comment by rajeshkanna777** [comment]
other phones are working fine but moto e is not working

**Comment by Poberro** [comment]
1. We don't know if it is not a phone issue (rather than SDK). You need to get a different BLE scanning app (there are plenty of them on Play) and check if it also has the same problem. 
2. Have you checked that Proximity SDK also has the same problem?
3. Please provide full logcat logs (without filtering) and [HCI bt snoop log](https://blog.bluetooth.com/debugging-bluetooth-with-an-android-app). Without them it is hard to tell what might be a problem.

**Comment by rajeshkanna777** [comment]
HI Poberro 

i check this one also 
https://play.google.com/store/apps/details?id=com.estimote.apps.main&hl=en

Its not working in moto e4 plus

**Comment by Poberro** [comment]
Estimote App is also using Estimote SDK. So if Estimote SDK is not working on on Moto E4 Plus, it is highly probable that Estimote App will also not work on that phone. Try different app, like [nRF Connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en) and check if it is able scan for some longer period of time. 
Some logs would be useful. I would also suggest checking [Proximity SDK](https://github.com/Estimote/Android-Proximity-SDK) and verifying if it works on Moto E4 Plus, because it has a new scanner that should solve many scanning problems on newer Android phones. 
Does it start scanning again when you turn Bluetooth off and on again?
