### ISSUE TITLE
.aar is missing

### ISSUE THREAD

**Issue by DogFive** [Estimote/Android-SDK#269]
The libraries for manual installation are missing.

https://github.com/Estimote/Android-SDK/blob/master/EstimoteSDK/estimote-sdk.aar

**Comment by wafel82** [comment]
Hi @DogFive

That's true - currently we are not delivering our SDK as a single package to be downloaded manually. As for now, the only supported way to get our SDKs is to use **JCenter** repository.
This is because we are  just switch to new SDK/Libraries structure which (we hope) will be easier and much more pleasant to be used. I'm sure we'll resume manual installation support for our new SDKs bundles, however I cannot provide you any exact date when it will  happen - just stay tuned :).
In  the meantime you can download our artifacts straight from JCenter repo - the latest version is available here:
[https://jcenter.bintray.com/com/estimote/sdk/1.4.0/](https://jcenter.bintray.com/com/estimote/sdk/1.4.0/)

Regards
Wojtek
