### ISSUE TITLE
How to Exclude Dependencies from Estimote because i already use Gson,Retrofit,RxJava,RxAndroid

### ISSUE THREAD

**Issue by jaichandervivekanandan** [Estimote/Android-SDK#271]
How to Exclude Dependencies from Estimote because i already use Gson,Retrofit,RxJava,RxAndroid etc due to that dex Merger Issue occurs,Any idea how to resolve this

**Comment by pawelDylag** [comment]
Hey @jaichandervivekanandan 

If you asking about this SDK (1.4.0), which is currently scheduled for deprecation, then my answer would be that there is no option to exclude it, because all those packages were manually repackaged into the resulting .aar.
I suggest switching to our new [ProximitySDK](https://github.com/Estimote/Android-Proximity-SDK) 🚀 , where we are using external dependencies through `gradle`, and so if you are using the same libraries as our SDK, then your `gradle` will compile only one version of that library (or will take the newest version). [Read more here](https://docs.gradle.org/current/userguide/dependency_management.html#sec:dependency_management_overview).

Also make sure to track our current development process in [this thread](https://forums.estimote.com/t/estimote-android-sdk-official-progress-reports/7450/1) on our forums. 

Regards, 
Paweł
