### ISSUE TITLE
Not getting notification when app is killed

### ISSUE THREAD

**Issue by gowthamidommeti** [Estimote/Android-SDK#274]
Hi,
I am not getting the notification if the app is killed otherwise am getting a notification. I want to display a notification if my App is killed also.Please help me to resolve this issue.

**Comment by pawelDylag** [comment]
Hey @gowthamidommeti 

Basically, this is a bad behaviour - as a user you don't want random notifications to pop up when no app is running. So be careful with that. Anyway, background notifications are working for Android 8.0+ in our [new ProximitySDK](https://github.com/Estimote/Android-Proximity-SDK) - you can check it and read more about [how to do it](https://github.com/Estimote/Android-Proximity-SDK#background-scanning-using-proximity-trigger-android-80). Otherwise its not possible in the old SDK.

Regards, 
Paweł
