### ISSUE TITLE
Ranging not working in android Nougat

### ISSUE THREAD

**Issue by kpprasanth** [Estimote/Android-SDK#284]
I am using motorola with android version 7. Ranging not working even the app is in foreground and it works fine in all other devices.  While checking with log i am getting 
"I/BluetoothLeScanner: startRegisteration: mLeScanClients={com.estimote.coresdk.scanning.bluetooth.adapters.LollipopBluetoothAdapter$1@14f05d=android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper@f14ddd2}".

**Comment by Poberro** [comment]
1. This SDK is deprecated for scanning (there is a note on main page). You should try to switch to [Proximity SDK](https://github.com/Estimote/Android-Proximity-SDK)
1. By your description is seems that it does not work on particular phone model, but it works fine on others. So it seems that is a phone issue rather than a bug in SDK. 
2. Motorola have more than several phone models. Which one are you using?
3. This log message does not says much. It only tells that scan callback has been registered. Can you provide more logs?

Please fill provided template when submitting an issue. It really speeds up investigation.

**Comment by kpprasanth** [comment]
Hi Poberro,
  I am using Motorola E4 plus(android 7.1) in which ranging not working and I have tested using Motorola E2(android 5.1) where the ranging works fine. 
SDK Version : 1.4.1

**Comment by Poberro** [comment]
Can you provide some logs (from logcat and from [BT Snoop log](https://blog.bluetooth.com/debugging-bluetooth-with-an-android-app))? I need to see if there are some messages from Android that will tell me why it is not scanning.

**Comment by Poberro** [comment]
No logs provided. Closing. 
Scanning and Monitoring is deprecated in this SDK. Please use 
https://github.com/Estimote/Android-Proximity-SDK
