### ISSUE TITLE
How can I continue ranging/monitoring when the app is in background or app is closed?

### ISSUE THREAD

**Issue by khobaib** [Estimote/Android-SDK#62]
I am working with estimote beacon demo app(Android) & created one virtual beacon with the estimote iOS app. It's working fine when the activity is in the foreground - I can see the beacon in the list. 

The problem is when the activity (where I started ranging/monitoring) gets destroyed, beaconManager stops working as in onDestroy method I disconnected beaconManager. It totally hurts the purpose of using beacon in the first place - as we expect the app can sense a beacon even if the app is closed or app is in background(in activity stack of Android). The proper scenario would be - we want the user gets notified to something if the app is installed & if he comes into the range of a beacon.

Do you think it is possible? Perhaps with android Service?

**Comment by danieltigse** [comment]
is this fixed in version 0.13.0 ?? Because is happening the same to me. App stop monitoring when the system kill it.

**Comment by pawelDylag** [comment]
Hey @danieltigse 
Here are some docs describing how to handle monitoring after system kills your app:
https://github.com/Estimote/Android-SDK/blob/master/DOC_monitoring_after_restart.md
Tell me if that helps - if not, we will proceed further and take a deeper look into this problem.

**Comment by danieltigse** [comment]
It doesn't helps. Maybe this could work only when the phone is rebooted but the problem is when the system kills the app because of low memory. You should have a service running in background or maybe an option to decide if the developer want a the service running forever or not.

**Comment by VitorHFLopes** [comment]
I have a similar problem :(

I looked at Android Configs > Developer > In Execution and when the app is in foreground or background (not killed), the BeaconService is in "services in execution" and works fine. But when I kill the app (remove from task manager) the BeaconService is moved to "services in cache" and the app/android stops the background monitoring.

I tried to manage the `BeaconManager.setBackgroundScanPeriod()` for test, but without success :(

Does anyone knows how to "stuck" the service in "services in execution"? Or maybe if this is an Android behavior, how can I handle this?

**Comment by oferRounds** [comment]
@pawelDylag any solution to this perhaps?

**Comment by oferRounds** [comment]
The link you added above is broken... :)

**Comment by pawelDylag** [comment]
Hey guys! 

We are moving to the new version of our SDK, called ProximitySDK. It's currently in `ALPHA` stage, but will support background monitoring. I encourage you to read this topic on our [forums](https://forums.estimote.com/t/changes-to-android-sdk-current-progress/7450).

Also, the `alpha` version of our new sdk is available on [proximity-sdk branch](https://github.com/Estimote/Android-SDK/tree/proximity-sdk). 

Consider using the new SDK, because we made lots of upgrades to scanning mechanism, and it will work also in the background. You can read more in the links I provided you above. 

Cheers!

**Comment by oferRounds** [comment]
@pawelDylag thanks! Does `background` refers also to the scenario where the user kills the app?

**Comment by pawelDylag** [comment]
@oferRounds  Yes, but it needs to be done regarding the official Android guidelines - we allow to run your scanning in the background (using foreground service), but you need to provide a `notification` object. [Read more here.](https://forums.estimote.com/t/alpha-4-monitoring/7516/2)

**Comment by oferRounds** [comment]
Cool! Will read. 

Also, one more question please: are there any plans to add an SDK for React Native?

**Comment by pawelDylag** [comment]
@oferRounds Not for now. Fortunately, we got more and more requests for SDK supporting React Native, and we will probably consider doing something about it. Yet, probably not this year.

**Comment by oferRounds** [comment]
Got you, thanks!

**Comment by oferRounds** [comment]
Hi @pawelDylag 

Reading on Android docs I see on _Running a service in the foreground_, it says:

> A foreground service must provide a notification for the status bar, which is placed under the Ongoing heading. This means that the notification cannot be dismissed unless the service is either stopped or removed from the foreground.

I am new to Android (coming from iOS) - but If I understand right, this kind of banner/notification is kind of not pleasant to the user (a banner which is "stuck" there). Isn’t there a nicer way to workaround it, and still follow Android guidelines? (Something similar to iOS where the app is registered in the OS for the Beacon, and then woken app when the device enters the region)

I am building an app which allow companies/employees to automatically track their time at work.

**Comment by pawelDylag** [comment]
Hey @oferRounds 

I won't agree with the statement, that the notification is unpleasant. It informs the user, that something is doing heavy task in the background. Like Spotify music player, downloading progress, screen recording, etc. Our beacon scanning is using BLE, which somehow drains the battery, and Android will easily kill it, unless you show an explicit notification. In my personal opinion, this solution is great, because you, as a user, know exactly what is happening under the hood. You can modify the notification though - add buttons to stop scanning, or change the text. [Read more here](https://developer.android.com/training/notify-user/build-notification.html).  

This may seem a little bit odd to a person coming from the land of iOS, but this is how Android does stuff :) 

There are some possibilities to register beacon scanning in OS, but this is not very reliable, and won't work with our proximity algorithms. Maybe in the future we will incorporate this mechanism to work with our stack, but this is to be decided.

**Comment by oferRounds** [comment]
@pawelDylag - thanks for the detailed answer!

Two questions:
1. Form your experience, solution like this also not feasible? https://stackoverflow.com/questions/30222409/android-broadcast-receiver-bluetooth-events-catching
Meaning the system, can also kill it?

My concern is that compering to Spotify, for example, where the user chose to play the song - therefore it’s easy for him to understand – in our case — clock work — this will be harder for him to understand the justification. Your thoughts?

2. In iOS - I’m interested only in mentoring, is this also not reliable?

**Comment by oferRounds** [comment]
Hi @pawelDylag 

I’m trying to integrate the alpha sdk, buf facing an issue. Probably because I’m coming from iOS...

I followed your example and there is this line:
`notification = NotificationCreator().create(this)`

What is the `NotificationCreator`? I couldn’t find it. I’m writing in Java.

**Comment by pawelDylag** [comment]
Hey! @oferRounds 
1. The broadcast receiver, according to your stackoverflow link, is the solution if you want to know only if bluetooth was turned on or off. This will trigger your app then, but does not contain scan results. So is useless for your case. 
2. You can always use `startWithSimpleScanner` that doesn't require notification to show, but the scanning will probably be killed after the user exits from your app. 
3. `NotificationCreator` is an object that handles proper notification creation. Old Android versions require simple `Notification` object to be created. Since Android version `8.0`, you need to declare an `NotificationChannel` for your app. [Read more here](https://developer.android.com/guide/topics/ui/notifiers/notifications.html). 
Our `NotificationCreator` is a custom object, that was only included in our [example app](https://github.com/Estimote/Android-SDK/tree/proximity-sdk/example/ProximityApp). It's not included in our SDK, so you should create one on your own, or copy our solution from example app. 

Happy coding!

**Comment by pawelDylag** [comment]
Oh, and by the way - if you got any more questions, please create a thread on our [forums](https://forums.estimote.com/c/android-sdk). It will be easier for me to track it.

**Comment by oferRounds** [comment]
@pawelDylag 

Thanks again for the detailed answer!

If I have another issue, I will post in the forum, but for now, just to end this, 2 following questions:
1. Will the notification be shown also when the user just moved the app to the background (and not killed it via the app switcher)?
2. This service, how much does it effect the battery and what exactly does it do? (i.e., it’s not that clear to me, as in iOS the app just signs up with the OS to get awaken when the exact beacon is detected, and no extra work is need to be done by the app)

**Comment by oferRounds** [comment]
@pawelDylag - getting this crash after integrating the alpha version... Could you have a look?

http://crashes.to/s/a46eb54e694

**Comment by wafel82** [comment]
Hi @oferRounds,

At the first glance it looks like such crash may occur when application is
attempting to initialize our sdk while Bluetooth is disabled on the device.
In such case Android api returns null as a Bluetooth Adapter instance. It
appears we are not handling this situation properly :(.

We'll investigate it further and let you know when you can expect new sdk
version with fix included - stay tuned :)

Regards
Wojtek
